---
- name: Import Nodesource RPM key with rpm_key directly.
  rpm_key:
    key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: not curl_nodesource_rpm

- name: Download Nodesource RPM key with Curl.
  shell: curl https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL -o /tmp/nodesource.gpg
  args:
    creates: /tmp/nodesource.gpg
  when: curl_nodesource_rpm

- name: Import Nodesource RPM key from file. 
  rpm_key:
    key: /tmp/nodesource.gpg
    state: present
  when: curl_nodesource_rpm

- name: Add Nodesource repositories for Node.js.
  yum:
    name: "https://rpm.nodesource.com/pub/el/\
      {{ ansible_distribution_major_version }}/{{ ansible_architecture }}/\
      nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present
  when: not curl_nodesource_rpm

- name: Download Nodesource rpm file for Node.js.
  shell: "curl https://rpm.nodesource.com/pub/el/\
      {{ ansible_distribution_major_version }}/{{ ansible_architecture }}/\
      nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm \
      -o /tmp/nodesource.rpm"
  args:
    creates: /tmp/nodesource.rpm
  when: curl_nodesource_rpm

- name: Add Nodesource repositories from rpm file.
  yum:
    name: /tmp/nodesource.rpm
    state: present
  when: curl_nodesource_rpm

- name: Ensure Node.js and npm are installed.
  yum: "name=nodejs-{{ nodejs_version[0] }}.* state=present enablerepo='epel,nodesource'"
